"use client";
import { AnimatePresence, motion } from "motion/react";
import { ArrowRight, Check, ChevronRight, Info, Plus, Search, Sparkles, X, Zap } from "lucide-react";
import { useMemo, useState } from "react";

type Course={id:string;code:string;title:string;section:string;crn:string;credits:number;days:string;start:number;end:number;place:string;seats:number;requirement:string;unlocks:string;prereq:boolean;linked?:string;professor:string;groups:string[]};
const C=(id:string,code:string,title:string,section:string,crn:string,credits:number,days:string,start:number,end:number,place:string,seats:number,requirement:string,unlocks:string,groups:string[],extra:Partial<Course>={}):Course=>({id,code,title,section,crn,credits,days,start,end,place,seats,requirement,unlocks,groups,prereq:true,professor:"GT Faculty",...extra});
const catalog:Course[]=[
 C("cs1301-a","CS 1301","Introduction to Computing","A","81721",3,"MWF",10,11,"Clough",4,"Institutional Priority","CS 1331",["core","computing","engineering","science","business"] ,{professor:"Dr. Rivera"}),
 C("cs1301-c","CS 1301","Introduction to Computing","C","81728",3,"MWF",12,13,"Clough",18,"Institutional Priority","CS 1331",["core","computing","engineering","science","business"],{professor:"Dr. Rivera"}),
 C("cs1331","CS 1331","Object-Oriented Programming","B","81841",3,"TR",13,14,"Klaus",14,"Field of Study","CS 1332 and CS 2110",["computing","math-computing"],{prereq:false,professor:"Dr. Shah"}),
 C("math1551","MATH 1551","Differential Calculus","D","82106",2,"MWF",9,10,"Skiles",24,"Math requirement","MATH 1552",["core","engineering","computing","science","math-computing"]),
 C("math1552","MATH 1552","Integral Calculus","B","82314",4,"TR",9,11,"Skiles",12,"Math requirement","MATH 2551",["core","engineering","computing","science","math-computing"],{professor:"Prof. Chen"}),
 C("math1554","MATH 1554","Linear Algebra","C","82366",4,"MWF",14,15,"Clough",19,"Major foundation","MATH/CS 2740",["computing","math-computing","engineering","science"]),
 C("chem1211","CHEM 1211K","Chemical Principles I","G","83042",4,"TR",11,12,"Molecular Science",8,"Lab science","CHEM 1212K",["core","engineering","science"],{linked:"chem-lab",professor:"Dr. Patel"}),
 C("chem-lab","CHEM 1211K","Chemical Principles Lab","G1","83049",0,"T",14,17,"Boggs",8,"Linked lab","CHEM 1212K",["core","engineering","science"]),
 C("phys2211","PHYS 2211","Introductory Physics I","J","83414",4,"MWF",13,14,"Howey",15,"Lab science","PHYS 2212",["core","engineering","science"]),
 C("biol1510","BIOS 1510","Biological Principles","A","83920",4,"TR",10,12,"Ford ES&T",13,"Lab science","BIOS 1520",["core","science"]),
 C("engl1101","ENGL 1101","English Composition I","L","81042",3,"MWF",9,10,"Skiles",22,"Writing requirement","ENGL 1102",["core","all"]),
 C("engl1102","ENGL 1102","English Composition II","P","81109",3,"MWF",11,12,"Skiles",21,"Writing requirement","Upper-level humanities",["core","all"],{professor:"Prof. Brooks"}),
 C("phil3127","PHIL 3127","Science, Technology & Human Values","A","84561",3,"TR",12,13,"DM Smith",16,"Humanities + Ethics","Ethics concentration",["core","all","liberal"],{professor:"Dr. Morgan"}),
 C("hist2112","HIST 2112","United States Since 1877","B","84611",3,"TR",15,16,"DM Smith",25,"US History/Government","Upper-level social science",["core","all","liberal"]),
 C("econ2105","ECON 2105","Principles of Macroeconomics","C","84803",3,"MWF",12,13,"Scheller",17,"Social science / Field of Study","ECON 2106",["core","business","liberal"]),
 C("mgt1100","MGT 1100","Introduction to Business","A","85014",3,"TR",10,11,"Scheller",28,"Business foundation","Scheller core",["business"]),
 C("arch1016","ARCH 1016","Introduction to Architecture","A","85220",3,"MWF",10,11,"East Architecture",11,"Design foundation","Architecture studio",["design"]),
 C("lmc2500","LMC 2500","Introduction to Film","D","85307",3,"TR",13,14,"Skiles",9,"Humanities / Major elective","Advanced LMC",["design","liberal","core"]),
 C("ae1601","AE 1601","Introduction to Aerospace Engineering","A","85601",1,"F",12,13,"Guggenheim",30,"Major introduction","AE design sequence",["aerospace","engineering"]),
 C("bmed1000","BMED 1000","Intro to Biomedical Engineering","A","85812",1,"F",11,12,"Whitaker",18,"Major introduction","BMED core",["biomedical","engineering"]),
];
const coreRequirements=["Wellness (2 hrs)","Institutional Priority / Computing","Mathematics & Quantitative Skills","US History / Government","Arts, Humanities & Ethics (6 hrs)","English 1101 + 1102","Lab Sciences (8 hrs)","Social Sciences (9 hrs)","Major Field of Study"];
const tourSteps=[
 {eyebrow:"WELCOME TO REGISTRATION COPILOT",title:"Build a registerable draft—one step at a time",text:"This workspace helps you explore courses, catch common problems, and prepare a draft before you open OSCAR. It never registers classes for you.",icon:"✦",tip:"Start by browsing the recommendations selected for your major."},
 {eyebrow:"1 · DEGREE PLAN & READINESS",title:"Know what still needs attention",text:"The left panel summarizes common degree areas and checks your draft for prerequisites, linked labs, conflicts, credit load, holds, and your time ticket.",icon:"✓",tip:"Registration Holds and Time Ticket are interactive—click them after you verify each item in OSCAR."},
 {eyebrow:"2 · FIND & ADD COURSES",title:"Search in everyday language",text:"Use the center search for a course code or ideas like humanities, lab science, or AI. Choose a tab, then press + to add a section to your draft.",icon:"+",tip:"Every added course immediately updates your readiness score and weekly calendar."},
 {eyebrow:"3 · TEST YOUR WEEK",title:"Spot schedule and walking problems",text:"Your weekly calendar makes overlaps visible. The campus panel demonstrates how walking time between buildings should be considered before choosing back-to-back sections.",icon:"⌖",tip:"Click any course on the weekly calendar to remove it and try another section."},
 {eyebrow:"4 · REVIEW BEFORE OSCAR",title:"Finish with a readiness review",text:"Use Review my plan to see every passing check and warning together. Fix warnings, keep backup sections, then confirm the real data in official OSCAR.",icon:"→",tip:"Course seats and details here are a hackathon demo, so OSCAR remains the source of truth."},
];
function groupFor(major:string){const m=major.toLowerCase();if(m.includes("mathematics and computing"))return"math-computing";if(m.includes("computer")||m.includes("computational"))return"computing";if(m.includes("business"))return"business";if(m.includes("architecture")||m.includes("design")||m.includes("music")||m.includes("urban"))return"design";if(m.includes("international")||m.includes("econom")||m.includes("policy")||m.includes("history")||m.includes("literature")||m.includes("language"))return"liberal";if(m.includes("aerospace"))return"aerospace";if(m.includes("biomedical"))return"biomedical";if(m.includes("engineering"))return"engineering";return"science"}

export default function RegistrationCopilot({major,onClose}:{major:string;onClose:()=>void}){
 const group=groupFor(major), [selected,setSelected]=useState<Course[]>([]),[query,setQuery]=useState(""),[answer,setAnswer]=useState(`Showing core and recommended first-year courses for ${major||"your major"}.`),[filter,setFilter]=useState<"recommended"|"core"|"all">("recommended"),[holdsClear,setHoldsClear]=useState(false),[ticketChecked,setTicketChecked]=useState(false),[showReview,setShowReview]=useState(false),[tourStep,setTourStep]=useState(()=>typeof window!=="undefined"&&localStorage.getItem("first-flight-copilot-tour")==="done"?-1:0);
 const credits=selected.reduce((n,c)=>n+c.credits,0), conflicts=selected.filter((a,i)=>selected.some((b,j)=>j>i&&a.days.split("").some(d=>b.days.includes(d))&&a.start<b.end&&b.start<a.end));
 const missingLab=selected.some(c=>c.id==="chem1211")&&!selected.some(c=>c.id==="chem-lab"),tightWalk=selected.some((a,i)=>selected.some((b,j)=>j>i&&a.days.split("").some(d=>b.days.includes(d))&&b.start===a.end&&a.place!==b.place));
 const checks=[["Courses selected",selected.length>0,"Add courses to your draft"],["Prerequisites",selected.every(c=>c.prereq),selected.some(c=>!c.prereq)?"One prerequisite needs advisor review":"Requirements appear satisfied"],["Linked sections",!missingLab,missingLab?"CHEM linked lab missing":"Linked sections valid"],["Time conflicts",conflicts.length===0,conflicts.length?"Overlapping meeting detected":"No overlaps detected"],["Walking time",!tightWalk,tightWalk?"One transition is too tight":"Transitions look workable"],["Credit load",credits>=12&&credits<=18,`${credits} of 12–18 credits`],["Registration holds",holdsClear,holdsClear?"Student confirmed status":"Check OSCAR status"],["Time ticket",ticketChecked,ticketChecked?"Student confirmed ticket":"Check Prepare for Registration"]] as const;
 const score=Math.round(checks.filter(c=>c[1]).length/checks.length*100), recommended=catalog.filter(c=>c.groups.includes(group)||c.groups.includes("all")||c.groups.includes("core"));
 const results=useMemo(()=>{const q=query.toLowerCase().trim();let list=filter==="all"?catalog:filter==="core"?catalog.filter(c=>c.groups.includes("core")||c.groups.includes("all")):recommended;if(q)list=list.filter(c=>`${c.code} ${c.title} ${c.requirement} ${c.unlocks}`.toLowerCase().includes(q)||q.includes("human")&&c.requirement.includes("Humanities")||q.includes("lab")&&c.requirement.includes("Lab")||q.includes("ai")&&["CS 1301","CS 1331","MATH 1554"].includes(c.code));return list},[query,filter,recommended]);
 function add(c:Course){if(selected.some(s=>s.id===c.id))return;setSelected(s=>[...s,c]);setAnswer(`${c.code} satisfies ${c.requirement}, unlocks ${c.unlocks}, and ${c.seats<6?"has limited seats":"has open seats in this demo snapshot"}.`)}
 function ask(e:React.FormEvent){e.preventDefault();setFilter("all");setAnswer(query.toLowerCase().includes("ai")?"I highlighted introductory computing and math courses that build toward AI. Always confirm your exact thread or concentration with an advisor.":`I found ${results.length} catalog matches. Add a section to see readiness update instantly.`)}
 const backup=catalog.find(c=>c.code==="CS 1301"&&!selected.some(s=>s.id===c.id)&&selected.some(s=>s.code==="CS 1301")),days=["M","T","W","R","F"];
 function closeTour(){localStorage.setItem("first-flight-copilot-tour","done");setTourStep(-1)}
 return <motion.div className="copilot-shell" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><header className="copilot-top"><div><button onClick={onClose} aria-label="Close"><X/></button><div className="copilot-logo"><Zap fill="currentColor"/></div><span><small>LEVEL 2 · ADVISORY PLANNER</small><b>Registration Copilot</b></span></div><div className="copilot-header-actions"><button className="replay-tour" onClick={()=>setTourStep(0)}><Info/> Tour</button><div className="readiness-pill"><span style={{"--score":`${score*3.6}deg`} as React.CSSProperties}><b>{score}%</b></span><div><small>READINESS</small><b>{score>=88?"Ready to review":score>=60?"Almost ready":"Build your plan"}</b></div></div></div></header>
 <div className="copilot-disclaimer"><Info/><p><b>Planning assistant—not OSCAR.</b> This curated catalog demonstrates the workflow. Verify current sections, prerequisites, seats, and degree applicability with OSCAR and your academic advisor.</p></div>
 <div className="copilot-grid"><aside className="requirements-panel"><small>YOUR DEGREE PLAN</small><h2>{major||"Undeclared"}</h2><p>First-year planning · Core IMPACTS</p><div className="core-list">{coreRequirements.map((r,i)=><div key={r}><span className={i<2?"started":""}>{i<2?"◐":"○"}</span><b>{r}</b></div>)}</div><h3>Readiness checklist</h3><p className="checklist-help"><span>☝</span><b>You confirm the gold rows.</b> The rest update automatically as you build your schedule.</p>{checks.map(([name,ok,detail])=>{const confirmable=name==="Registration holds"||name==="Time ticket";return <button className={`readiness-check ${ok?"valid":"warning"} ${confirmable?"confirmable":"automatic"}`} key={name} aria-pressed={confirmable?ok:undefined} onClick={()=>name==="Registration holds"?setHoldsClear(v=>!v):name==="Time ticket"?setTicketChecked(v=>!v):undefined}><span>{ok?<Check/>:"!"}</span><div><b>{name}</b><small>{detail}</small>{confirmable&&<em>{ok?"✓ Confirmed · click to undo":"CLICK TO CONFIRM"}</em>}</div>{confirmable&&<i>{ok?"DONE":"TAP"}</i>}</button>})}</aside>
 <main className="planner-main"><section className="ai-planner"><div className="ai-title"><Sparkles/><span><small>COURSE FINDER</small><b>{answer}</b></span></div><form onSubmit={ask}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder='Search “humanities,” “lab science,” “CS 1301,” or “AI”'/><button aria-label="Search"><Search/></button></form><div className="catalog-tabs"><button className={filter==="recommended"?"active":""} onClick={()=>{setFilter("recommended");setQuery("")}}>For {major||"my major"}</button><button className={filter==="core"?"active":""} onClick={()=>{setFilter("core");setQuery("")}}>Core requirements</button><button className={filter==="all"?"active":""} onClick={()=>{setFilter("all");setQuery("")}}>All {catalog.length} demo courses</button></div></section>
 <section className="course-results"><div className="section-title"><div><small>CURATED CATALOG · FALL DEMO</small><h2>{results.length} suitable courses</h2></div><Search/></div><div>{results.map(c=><article key={c.id}><div className="course-code"><b>{c.code}</b><small>SEC {c.section} · CRN {c.crn}</small></div><div className="course-info"><b>{c.title}</b><span>{c.days} · {c.start}:00–{c.end}:00 · {c.place}</span><p>✓ {c.requirement} · Unlocks {c.unlocks}</p></div><div className={c.seats<6?"low-seats":"seats"}>{c.seats} seats</div><button onClick={()=>add(c)} disabled={selected.some(s=>s.id===c.id)} aria-label={`Add ${c.code}`}>{selected.some(s=>s.id===c.id)?<Check/>:<Plus/>}</button></article>)}{results.length===0&&<div className="no-results"><b>No matching demo courses</b><span>Try a course code, “humanities,” “lab science,” or select All courses.</span></div>}</div></section>
 {backup&&<section className="backup-card"><span>⚡</span><div><small>BACKUP SECTION FOUND</small><b>{backup.code} Section {backup.section}</b><p>Same professor · {backup.seats} seats · fits this draft</p></div><button onClick={()=>setSelected(s=>[...s.filter(x=>x.code!==backup.code),backup])}>Replace section</button></section>}
 <section className="weekly-schedule"><div className="section-title"><div><small>CLICK A COURSE TO REMOVE IT</small><h2>Weekly schedule</h2></div><b>{credits} credits</b></div><div className="calendar-grid"><div className="time-axis">{[8,10,12,14,16,18].map(t=><span key={t}>{t>12?t-12:t}:00</span>)}</div>{days.map(day=><div className="day-column" key={day}><b>{day}</b>{selected.filter(c=>c.days.includes(day)).map(c=><motion.button layout key={c.id} style={{top:`${32+(c.start-8)*38}px`,height:`${Math.max(34,(c.end-c.start)*38)}px`}} onClick={()=>setSelected(s=>s.filter(x=>x.id!==c.id))}><strong>{c.code}</strong><small>{c.place}</small></motion.button>)}</div>)}</div></section></main>
 <aside className="campus-panel"><small>WALKING TIME PLANNER</small><h2>Illustrated Campus Section</h2><div className="sample-campus-map"><div className="road road-h"><i/><i/></div><div className="road road-v"><i/></div><span className="tree t1">♣</span><span className="tree t2">♣</span><span className="tree t3">♣</span><span className="tree t4">♣</span><div className="map-building paper"><i>PT</i><b>Paper<br/>Tricentennial</b></div><div className="map-building klaus"><i>KC</i><b>Klaus<br/>Computing</b></div><div className="map-building clough"><i>CL</i><b>Clough<br/>Commons</b></div><svg viewBox="0 0 260 250" preserveAspectRatio="none"><path className="route-one" d="M46 188 C82 168 93 112 147 90"/><path className="route-two" d="M153 86 C185 73 213 92 224 135"/><circle cx="46" cy="188" r="5"/><circle cx="150" cy="88" r="5"/><circle cx="224" cy="135" r="5"/></svg><span className="time-badge time-one">15 min</span><span className="time-badge time-two">7 min</span></div><div className="map-route-key"><div><span>A</span><b>Paper Tricentennial</b></div><ArrowRight/><em>15-minute walk</em><ArrowRight/><div><span>B</span><b>Klaus</b></div></div><div className="simple-answer"><b>🟢 Comfortable with a 20-minute gap</b><span>Continue to Clough in about 7 more minutes.</span></div>{selected.length>=2?<div className="your-transition"><small>YOUR FIRST TRANSITION</small><b>{selected[0].place} → {selected[1].place}</b><span>{selected[0].place===selected[1].place?"2":"9"}-minute walking estimate</span><em>Demo estimate—verify the actual route before registration.</em></div>:<p className="walk-explanation">Add two courses and your first transition will appear here.</p>}<button className="oscar-ready" onClick={()=>setShowReview(true)}>Review my plan <ChevronRight/></button></aside></div>
 <AnimatePresence>{showReview&&<motion.div className="plan-review-scrim" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className="plan-review" initial={{scale:.92,y:20}} animate={{scale:1,y:0}}><button className="review-close" onClick={()=>setShowReview(false)}><X/></button><small>REGISTRATION READINESS REVIEW</small><h2>{score}% ready</h2><p>{selected.length?`Your draft contains ${selected.length} sections and ${credits} credits.`:"Your draft is empty. Add courses before going to OSCAR."}</p><div>{checks.map(([n,ok,d])=><span className={ok?"pass":"fail"} key={n}>{ok?<Check/>:"!"}<b>{n}</b><small>{d}</small></span>)}</div><div className="review-actions"><button onClick={()=>setShowReview(false)}>Keep planning</button><a href="https://oscar.gatech.edu/" target="_blank" rel="noreferrer">Open official OSCAR <ArrowRight/></a></div><em>First Flight does not register courses or guarantee eligibility. Confirm everything in OSCAR.</em></motion.div></motion.div>}{tourStep>=0&&<motion.div className="copilot-tour-scrim" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.section className="copilot-tour" key={tourStep} initial={{scale:.94,y:20}} animate={{scale:1,y:0}}><button className="tour-skip" onClick={closeTour}>Skip tour</button><div className="tour-icon">{tourSteps[tourStep].icon}</div><small>{tourSteps[tourStep].eyebrow}</small><h2>{tourSteps[tourStep].title}</h2><p>{tourSteps[tourStep].text}</p><div className="tour-tip"><Sparkles/><span><b>Good to know</b>{tourSteps[tourStep].tip}</span></div><div className="tour-footer"><div>{tourSteps.map((_,i)=><i key={i} className={i===tourStep?"active":i<tourStep?"done":""}/>)}</div><span>{tourStep+1} / {tourSteps.length}</span><button disabled={tourStep===0} onClick={()=>setTourStep(s=>s-1)}>Back</button><button onClick={()=>tourStep===tourSteps.length-1?closeTour():setTourStep(s=>s+1)}>{tourStep===tourSteps.length-1?"Start planning":"Next"}<ArrowRight/></button></div></motion.section></motion.div>}</AnimatePresence></motion.div>
}
